import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Learning Webapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nvang.dev">Dang Nguyen!</a>
        </h1>

        <div className={styles.grid}>
          <a href="https://nvdang.dev" className={styles.card}>
            <h2>Learning  &rarr;</h2>
            <p>Learning information</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Testing &rarr;</h2>
            <p>Testing course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Relax &rarr;</h2>
            <p>Discover and find some interesting thing in your life</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Contact &rarr;</h2>
            <p>
              Go to nvdang.dev
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://nvdang.dev"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Dang Nguyen
        </a>
      </footer>
    </div>
  )
}
