import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Learning </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main} style={{marginTop: 50}}>
        <div className={styles.grid}>
          <a href="https://nvdang.dev" className={styles.card}>
            <h2>Learning  &rarr;</h2>
            <p>Information</p>
          </a>

          <a href="https://nvdang.dev" className={styles.card}>
            <h2>Testing &rarr;</h2>
            <p>Quizzes!</p>
          </a>

          <a
            href="https://nvdang.dev"
            className={styles.card}
          >
            <h2>Relax &rarr;</h2>
            <p>Discover</p>
          </a>

          <a
            href="https://nvdang.dev"
            className={styles.card}
          >
            <h2>Contact &rarr;</h2>
            <p>
            nvdang.dev
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://nvdang.dev"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Dang Nguyen
        </a>
      </footer>
    </div>
  )
}
